spring:
  datasource:
    driver-class-name: org.h2.Driver
    password:
    username: sa
    url: jdbc:h2:tcp://localhost/~/test
  jpa:
    hibernate:
      ddl-auto: create
      properties:
        hibernate:
          show_sql:true
          format_sql:true
server:
  port: 8099
